In [1]:
import cobra
import modelseedpy
import cobrakbase
from tqdm import tqdm
from cobrakbase.kbaseapi_cache import KBaseCache
config = cobra.Configuration()
#config.solver = 'cplex'
#config.solver = 'gurobi'

modelseedpy 0.4.0
cobrakbase 0.4.0

In [2]:
kbase = KBaseCache(path='/scratch/fliu/data/kbase/cache')

In [3]:
model_ids = set()
for i in kbase.list_workspace(186678):
    if i.type == 'KBaseFBA.FBAModel':
        if i.id.endswith('pyr.O2.gf'):
            model_ids.add(i.id)

In [4]:
data_methane = []
models = {}
for model_id in tqdm(model_ids):
    model = kbase.get_from_ws(model_id, 186678)
    models[model_id] = model
    if 'EX_cpd01024_e0' in model.reactions:
        model.objective = 'EX_cpd01024_e0'
        s = model.optimize()
        row_data = [
            model_id, s.objective_value, 
            [r.id for r in model.metabolites.cpd01024_c0.reactions]]
        data_methane.append(row_data)
        #print('!', row_data)

100%|██████████| 304/304 [09:44<00:00,  1.92s/it]

In [12]:
from cobra.core import Reaction
for model_id in models:
    model = models[model_id]
    if 'cpd25960_c0' in model.metabolites and 'EX_cpd25960_c0' not in model.reactions:
        ex = Reaction('EX_cpd25960_c0', 'exchange for MePn', '', -1000, 1000)
        ex.add_metabolites({model.metabolites.cpd25960_c0: -1})
        model.add_reactions([ex])
        print('!', model_id)

In [15]:
def _get_props(model, rxn_id, s):
    flux, genes = (None, None)
    if rxn_id in model.reactions:
        rxn = model.reactions.get_by_id(rxn_id)
        flux = s.fluxes[rxn_id]
        genes = {x.id for x in rxn.genes}
    return flux, genes

In [20]:
for model_id in models:
    model = models[model_id]
    
    if 'EX_cpd01024_e0' in model.reactions:
        model.objective = 'EX_cpd01024_e0'
        s = model.optimize()
        print(model_id, s.objective_value),
        print('\t', 'rxn26456_c0' in model.reactions, _get_props(model, 'rxn26456_c0', s))
        print('\t', 'rxn26457_c0' in model.reactions, _get_props(model, 'rxn26457_c0', s))
        print('\t', 'rxn43120_c0' in model.reactions, _get_props(model, 'rxn43120_c0', s))
        print()
    else:
        print(model_id, ['rxn26456_c0' in model.reactions, 'rxn26457_c0' in model.reactions, 'rxn43120_c0' in model.reactions], '-')
        print()

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1733', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1739', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1735', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1739_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1734_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1734', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1733_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1735_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1744_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1742_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1744', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1742'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1737_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.CDS.1737'})

Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, set())
	 True (0.0, set())
	 False (None, None)

Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.80.pangenome.RAST.glm4ec.pyr.O2.gf 50.00000000000001
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.69.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (49.999999999999986, set())
	 True (49.999999999999986, set())
	 True (49.999999999999986, set())

Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2.gf 50.000000000000014
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.54.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.12.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.9.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (50.00000000000001, set())
	 True (50.0, set())
	 True (49.99999999999999, set())

Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (0.0, {'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.84_mRNA', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.81', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.84', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.86_mRNA', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.85_mRNA', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.85', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.86', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.81_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.78', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.78_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.83_mRNA', 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.CDS.83'})

Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.33.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (0.0, set())
	 True (0.0, set())
	 True (0.0, set())

Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (29.411764705882163, set())
	 True (29.411764705882167, set())
	 False (None, None)

Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.22.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.36.pangenome.RAST.glm4ec.pyr.O2.gf 49.99999999999999
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf 100.00000000000001
	 True (49.99999999999999, set())
	 True (49.99999999999999, {'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.CDS.254', 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.CDS.254_mRNA'})
	 False (None, None)

Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_concoct_out.44.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.2.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2.gf 1000.0
	 True (71.34109001837128, set())
	 True (71.34109001837128, set())
	 False (None, None)

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.31.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.44.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (40.07936507936511, set())
	 True (40.07936507936511, set())
	 True (40.07936507936512, set())

Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.93.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2.gf 100.00000000000001
	 True (11.20689655172417, set())
	 True (11.20689655172418, set())
	 False (None, None)

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (100.00000000000003, set())
	 True (100.0, set())
	 True (100.0, set())

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.50.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4409', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2042', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2055_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2058', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2042_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2055', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2041_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4409_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2040_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2040', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2058_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2041'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4407_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2059', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2059_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4407'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2036', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2036_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2056_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4411_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.2056', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.CDS.4411'})

Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.6.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (0.0, set())
	 True (0.0, set())
	 True (0.0, set())

Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf 100.00000000000001
	 True (0.0, {'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.674_mRNA', 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.671', 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.671_mRNA', 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.674'})
	 True (0.0, {'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.675', 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.CDS.675_mRNA'})
	 False (None, None)

Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (100.00000000000001, set())
	 True (100.0, set())
	 True (100.0, set())

Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.50.pangenome.RAST.glm4ec.pyr.O2.gf 50.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (50.000000000000014, set())
	 True (50.00000000000001, set())
	 True (50.0, set())

Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (50.0, set())
	 True (50.0, set())
	 True (49.99999999999999, set())

Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.pangenome.RAST.glm4ec.pyr.O2.gf 50.00000000000001
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, set())
	 True (0.0, set())
	 True (0.0, set())

Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2.gf 99.99999999999999
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_metabat.42.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (5.781779476683235e-15, set())
	 True (5.781779476683235e-15, set())
	 True (5.781779476683236e-15, set())

Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.pangenome.RAST.glm4ec.pyr.O2.gf 99.99999999999999
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.47.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (5.441637116517409e-15, set())
	 True (5.441637116517409e-15, set())
	 True (5.441637116517408e-15, set())

Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.10.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (1.980198019801977, set())
	 True (1.9801980198019773, set())
	 False (None, None)

Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.11.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_maxbin.022.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (-1.4495631012477223e-14, set())
	 True (-1.4495631012477223e-14, set())
	 True (-1.4495631012477223e-14, set())

Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.54.pangenome.RAST.glm4ec.pyr.O2.gf [True, True, True] -

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1888_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1886_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1886', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1887_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1891_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1887', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1891', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1888'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.3470_mRNA', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.3470', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1894', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1894_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1889', 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1889_mRNA'})

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, {'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1434', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1435', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1435_mRNA', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1436_mRNA', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1436', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1440', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1440_mRNA', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1434_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1443', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1443_mRNA'})
	 True (0.0, {'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1438_mRNA', 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.CDS.1438'})

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.45.pangenome.RAST.glm4ec.pyr.O2.gf 99.99999999999997
	 True (99.99999999999997, set())
	 True (99.99999999999999, set())
	 True (100.0, set())

Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_metabat.4.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.15.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.25.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.63.pangenome.RAST.glm4ec.pyr.O2.gf 100.00000000000003
	 True (100.00000000000001, set())
	 True (100.00000000000001, set())
	 True (100.0, set())

Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 True (0.0, set())
	 True (0.0, set())
	 True (0.0, set())

Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.25.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.34.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (0.0, set())
	 True (1.5128034919988307e-14, set())
	 True (1.5128034919988307e-14, set())

Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.49.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.10.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.pangenome.RAST.glm4ec.pyr.O2.gf [False, False, False] -

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (50.000000000000014, set())
	 True (50.000000000000014, set())
	 True (50.000000000000014, set())

Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.30.pangenome.RAST.glm4ec.pyr.O2.gf 100.0
	 True (100.00000000000001, set())
	 True (100.0, set())
	 True (100.0, set())

Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.pangenome.RAST.glm4ec.pyr.O2.gf 49.99999999999999
	 True (0.0, set())
	 True (0.0, set())
	 False (None, None)

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.pangenome.RAST.glm4ec.pyr.O2.gf 100.00000000000001
	 False (None, None)
	 False (None, None)
	 False (None, None)

Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.58.pangenome.RAST.glm4ec.pyr.O2.gf 0.0
	 False (None, None)
	 False (None, None)

In [6]:
for o in data_methane:
    print(o)

['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.98.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn26459_c0']]
['Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn43120_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn00843_c0', 'rxn10471_c0', 'rxn26459_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.120.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.28.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn00844_c0']]
['Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.8.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.58.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.91.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn43120_c0', 'rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.7.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn43120_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.43.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.5.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.4.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.28.pangenome.RAST.glm4ec.pyr.O2.gf', 25.0, ['rxn03127_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn26459_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn43120_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn26459_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn43120_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_maxbin.047.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.52.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.33.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn43120_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.4.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn00843_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.38.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn26459_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.32.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.50.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn03127_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_maxbin.028.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_concoct_out.44.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn26459_c0', 'rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.34.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn26459_c0', 'rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.104.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0', 'rxn10471_c0', 'rxn00844_c0']]
['Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.36.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaGSF2_C_D1_MG_DASTool_bins_concoct_out.13.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.80.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.23.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.22.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.26.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.80.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn03127_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn26459_c0']]
['Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.10.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn37117_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn43120_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_concoct_out.2.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.5.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00844_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.68.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.65.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.22.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.20.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.6.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0', 'rxn00844_c0']]
['Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.6.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn03127_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2.gf', 1000.0, ['rxn26459_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.29.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.23.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.59.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.45.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.55.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.36.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.25.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.44.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.109.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn00844_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.87.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_maxbin.009.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.45.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.2.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_maxbin.035.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn26459_c0']]
['Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_metabat.9.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn03127_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.78.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn26459_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.pangenome.RAST.glm4ec.pyr.O2.gf', 150.0, ['rxn00843_c0', 'rxn26459_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.25.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.49.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn03127_c0', 'rxn43120_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn43120_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.110.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0', 'rxn26459_c0']]
['Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.pangenome.RAST.glm4ec.pyr.O2.gf', 200.0, ['rxn10471_c0', 'rxn00844_c0', 'rxn43120_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.89.pangenome.RAST.glm4ec.pyr.O2.gf', 50.0, ['rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.30.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn10471_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.47.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn00843_c0', 'rxn43120_c0', 'rxn10471_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn26459_c0', 'rxn10471_c0', 'rxn00843_c0']]
['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.63.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn03127_c0']]
['Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn10471_c0', 'rxn03127_c0', 'rxn00843_c0', 'rxn43120_c0']]
['Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_maxbin.037.pangenome.RAST.glm4ec.pyr.O2.gf', 0.0, ['rxn00843_c0', 'rxn10471_c0']]
['Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.33.pangenome.RAST.glm4ec.pyr.O2.gf', 100.0, ['rxn43120_c0', 'rxn10471_c0', 'rxn00843_c0', 'rxn03127_c0']]

{'rxn03127_c0', 'rxn10471_c0'}

100.0

In [19]:
model.metabolites.cpd01024_c0

In [20]:
model.reactions.rxn03127_c0

In [2]:
ws_reg = 155805
ws_enh = 186678

In [4]:
model_reg = kbase.get_from_ws('Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2', ws_reg)
model_enh = kbase.get_from_ws('Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2', ws_enh)

In [23]:
model_reg = kbase.get_from_ws('Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.contigs__.RAST.pyr.O2', ws_reg)
model_enh = kbase.get_from_ws('Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.pangenome.RAST.glm4ec.pyr.O2', ws_enh)

In [28]:
model_reg.template_ref

'155805/767/2'

In [29]:
model_enh.template_ref

'186678/12/1'

In [30]:
kbase.get_object_info(model_reg.template_ref).id

'template_v6gn_methylphosphonate_deg'

In [31]:
kbase.get_object_info(model_enh.template_ref).id

'template_v6gn_methylphosphonate_deg'

In [26]:
len(model_reg.genes), len(model_enh.genes)

(1431, 1505)

In [27]:
len(model_reg.reactions), len(model_enh.reactions)

(1078, 1100)

In [21]:
model_enh.summary()

In [15]:
for rxn_id in {x.id for x in model_enh.reactions} - {x.id for x in model_reg.reactions}:
    print(model_enh.reactions.get_by_id(rxn_id).build_reaction_string(True))

ADP [c0] + H+ [c0] + Nicotinate ribonucleotide [c0] <-- ATP [c0] + Nicotinate D-ribonucleoside [c0]
H2O [c0] + O2 [c0] + L-Lysine [c0] --> NH3 [c0] + H2O2 [c0] + 2-Oxo-6-aminocaproate [c0]
GTP [c0] + Mevalonic acid [c0] --> GDP [c0] + H+ [c0] + 5-phosphomevalonate [c0]
NADP [c0] + Phosphate [c0] + Glyceraldehyde3-phosphate [c0] <-- NADPH [c0] + H+ [c0] + 1,3-Bisphospho-D-glycerate [c0]
H2O [c0] + N-acetyl-LL-2,6-diaminopimelate [c0] --> Acetate [c0] + LL-2,6-Diaminopimelate [c0]
2 Isopentenyldiphosphate [c0] + Geranylgeranyl diphosphate [c0] --> 2 PPi [c0] + 2 H+ [c0] + all-trans-Hexaprenyl diphosphate [c0]
L-Glutamine [c0] + Glyceraldehyde3-phosphate [c0] + D-Ribulose5-phosphate [c0] --> 3 H2O [c0] + Phosphate [c0] + Pyridoxal phosphate [c0] + L-Glutamate [c0] + H+ [c0]
NAD [c0] + Glycolate [c0] <-- NADH [c0] + Glyoxalate [c0] + H+ [c0]
2 NADP [c0] + CoA [c0] + Mevalonic acid [c0] <-- 2 NADPH [c0] + 2 H+ [c0] + HMG-CoA [c0]
NADH [c0] + NADP [c0] + 2 H+ [e0] --> NAD [c0] + NADPH [c0] + 2 H+ [c0]
ATP [c0] + CoA [c0] + Glutarate [c0] --> PPi [c0] + AMP [c0] + Glutaryl-CoA [c0]
2-Oxoglutarate [c0] + 5-Aminopentanoate [c0] --> L-Glutamate [c0] + 5-Oxopentanoate [c0]
NAD [c0] + NADPH [c0] --> NADH [c0] + NADP [c0]
GSH [e0] <=>
H2O [c0] + ATP [c0] + GSH [e0] --> ADP [c0] + Phosphate [c0] + GSH [c0] + H+ [c0]
K+ [e0] <-- K+ [c0]
H2O [c0] + NAD [c0] + p-Hydroxybenzaldehyde [c0] --> NADH [c0] + 2 H+ [c0] + 4-Hydroxybenzoate [c0]
S-Adenosyl-L-methionine [c0] + 2-Demethylmenaquinol 8 [c0] --> S-Adenosyl-homocysteine [c0] + H+ [c0] + Menaquinol 8 [c0]
H+ [c0] + dATP [c0] + GMP [c0] --> GDP [c0] + dADP [c0]
CoA [c0] + H+ [c0] + HMG-CoA [c0] <-- H2O [c0] + Acetyl-CoA [c0] + Acetoacetyl-CoA [c0]
4-Maleylacetoacetate [c0] <=> Fumarylacetoacetate [c0]
ATP [c0] + H+ [c0] + 5-phosphomevalonate [c0] --> ADP [c0] + 5-diphosphomevalonate [c0]
2-Oxoglutarate [c0] + N-acetyl-LL-2,6-diaminopimelate [c0] <-- L-Glutamate [c0] + L-2-Acetamido-6-oxopimelate [c0]
NADP [c0] + (R)-2,3-Dihydroxy-3-methylbutanoate [c0] <=> NADPH [c0] + H+ [c0] + (S)-2-Acetolactate [c0]
2 H2O [c0] + NADP [c0] + 1-Pyrroline-5-carboxylate [c0] <=> NADPH [c0] + L-Glutamate [c0] + H+ [c0]
ATP [c0] + Adenosyl cobinamide [c0] --> ADP [c0] + H+ [c0] + Adenosyl cobinamide phosphate [c0]
ATP [c0] + L-Tyrosine [c0] + L-Cysteine [c0] + 1-deoxy-D-xylulose5-phosphate [c0] --> H2O [c0] + CO2 [c0] + PPi [c0] + AMP [c0] + L-Alanine [c0] + 2 H+ [c0] + 4-Methyl-5--2-phosphoethyl-thiazole [c0] + 4-Hydroxy-benzylalcohol [c0]
ATP [c0] + 5-diphosphomevalonate [c0] --> ADP [c0] + Phosphate [c0] + CO2 [c0] + Isopentenyldiphosphate [c0]
NAD [c0] + 4-Hydroxy-benzylalcohol [c0] --> NADH [c0] + H+ [c0] + p-Hydroxybenzaldehyde [c0]
H2O [c0] + Acetyl-CoA [c0] + tetrahydrodipicolinate [c0] --> CoA [c0] + L-2-Acetamido-6-oxopimelate [c0]
ATP [c0] + GTP [c0] --> AMP [c0] + 2 H+ [c0] + Guanosine 5'-triphosphate,3'-diphosphate [c0]
ATP [c0] + Formate [c0] + GAR [c0] --> ADP [c0] + Phosphate [c0] + H+ [c0] + N-Formyl-GAR [c0]

In [18]:
for rxn_id in {x.id for x in model_reg.reactions} - {x.id for x in model_enh.reactions}:
    print(rxn_id, model_reg.reactions.get_by_id(rxn_id).build_reaction_string(True))

rxn03907_c0 CTP [c0] + 2-C-methyl-D-erythritol4-phosphate [c0] --> PPi [c0] + 4--cytidine5-diphospho-2-C-methyl-D-erythritol [c0]
rxn01424_c0 H+ [c0] + Lipoamide [c0] + 2-Oxoadipate [c0] --> CO2 [c0] + S-Glutaryldihydrolipoamide [c0]
rxn00239_c0 ATP [c0] + H+ [c0] + GMP [c0] --> ADP [c0] + GDP [c0]
rxn08981_c0 H2O [c0] + ATP [c0] + PRPP [c0] + Niacin [c0] --> ADP [c0] + Phosphate [c0] + PPi [c0] + H+ [c0] + Nicotinate ribonucleotide [c0]
rxn02939_c0 NAD [c0] + 4-Phosphoerythronate [c0] --> NADH [c0] + H+ [c0] + 2-Oxo-3-hydroxy-4-phosphobutanoate [c0]
rxn00966_c0 Pyruvate [c0] + 4-Hydroxybenzoate [c0] <-- Chorismate [c0]
rxn03004_c0 10-Formyltetrahydrofolate [c0] + GAR [c0] --> H+ [c0] + Tetrahydrofolate [c0] + N-Formyl-GAR [c0]
rxn01873_c0 Glutaryl-CoA [c0] + Dihydrolipoamide [c0] <-- CoA [c0] + H+ [c0] + S-Glutaryldihydrolipoamide [c0]
rxn04413_c0 GTP [c0] + Adenosyl cobinamide [c0] --> GDP [c0] + H+ [c0] + Adenosyl cobinamide phosphate [c0]
rxn10094_c0 S-Adenosyl-L-methionine [c0] + 2-Demethylmenaquinone 8 [c0] --> S-Adenosyl-homocysteine [c0] + H+ [c0] + Menaquinone 8 [c0]
rxn43837_c0 2 Reducedferredoxin [c0] + C15812 [c0] + Adenylated-ThiS-Proteins [c0] --> AMP [c0] + 2 Oxidizedferredoxin [c0] + Sulfur-Carrier-Proteins-ThiI [c0] + Thiocarboxyadenylated-ThiS-Proteins [c0]
rxn13477_c0 3 Isopentenyldiphosphate [c0] + Farnesyldiphosphate [c0] --> 3 PPi [c0] + 3 H+ [c0] + all-trans-Hexaprenyl diphosphate [c0]
rxn02226_c0 H2O [c0] + NAD [c0] + 2-Aminoadipate 6-semialdehyde [c0] --> NADH [c0] + 2 H+ [c0] + L-2-Aminoadipate [c0]
rxn01331_c0 H2O [c0] + NAD [c0] + D-Erythrose4-phosphate [c0] --> NADH [c0] + 2 H+ [c0] + 4-Phosphoerythronate [c0]
rxn03910_c0 2-phospho-4--cytidine5-diphospho-2-C-methyl-D-erythritol [c0] --> CMP [c0] + 2-C-methyl-D-erythritol2-4-cyclodiphosphate [c0]
rxn27289_c0 1-deoxy-D-xylulose5-phosphate [c0] + Iminoglycine [c0] + Thiocarboxyadenylated-ThiS-Proteins [c0] --> 2 H2O [c0] + H+ [c0] + 2-[(2R,5Z)-2-Carboxy-4-methylthiazol-5(2H)-ylidene]ethyl phosphate [c0] + Thi-S [c0]
rxn03031_c0 H2O [c0] + Succinyl-CoA [c0] + tetrahydrodipicolinate [c0] --> CoA [c0] + N-Succinyl-L-2-amino-6-oxopimelate [c0]
rxn01423_c0 2-Oxoglutarate [c0] + L-2-Aminoadipate [c0] --> L-Glutamate [c0] + 2-Oxoadipate [c0]
rxn00003_c0 CO2 [c0] + ALCTT [c0] <-- 2 Pyruvate [c0] + H+ [c0]

In [22]:
for info in kbase.list_workspace(ws_reg):
    if info.type == 'KBaseFBA.FBAModel':
        print(info.id, info.type)

Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_maxbin.022.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.7.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.18.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_concoct_out.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.15.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.100.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.26.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.89.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.13.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.25.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.89.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.37.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.23.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.15.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.51.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.44.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.4.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.36.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.58.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.11.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.11.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.119.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.39.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.5.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.10.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.53.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.65.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.11.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.18.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_maxbin.062.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.59.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.49.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.20.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.61.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.25.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.005.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.98.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.22.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_maxbin.047.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.109.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.30.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.59.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.43.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.58.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.9.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.33.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.6.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_maxbin.028.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.7.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.31.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.3.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.8.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.11.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.86.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.37.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.29.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.8.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.42.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_concoct_out.2.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.24.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.124.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.22.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.28.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.62.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.2.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_maxbin.014.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.110.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.7.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.47.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.50.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.29.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_metabat.4.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.84.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.38.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.40.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.104.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.017.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.80.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.8.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.42.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.22.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.34.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.37.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.1.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.120.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.27.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.26.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.71.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.43.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.9.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.45.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.15.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.69.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.23.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.78.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.67.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.12.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.13.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.87.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.34.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.16.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.10.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_metabat.42.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.30.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.49.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.13.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.28.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.26.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D1_MG_DASTool_bins_concoct_out.13.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.68.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.11.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.19.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.32.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.39.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.44.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.63.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.80.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.7.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_metabat.9.contigs__.RASTauxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.98.contigs__.RAST.auxo.mdl KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.10.contigs__.RASTauxo.mdl KBaseFBA.FBAModel

In [ ]:
for info in kbase.list_workspace(ws_enh):
    if info.type == 'KBaseFBA.FBAModel':
        kbase.get_from_ws(info.id, ws_enh)
        print(info.id, info.type)