In [2]:
import os
import json
from tqdm import tqdm
import cobra
import modelseedpy
import cobrakbase
import pandas as pd
from cobrakbase.kbaseapi_cache import KBaseCache
config = cobra.Configuration()
# config.solver = 'cplex'

In [3]:
kbase = KBaseCache(path='/scratch/fliu/data/kbase/cache')

In [4]:
genomes = {}
genome_assembly = {}
for info in tqdm(kbase.list_workspace(155805)):
    if info.type == 'KBaseGenomes.Genome':
        genome = kbase.get_from_ws(str(info))
        assembly = kbase.get_from_ws(genome.assembly_ref)
        genomes[info.id] = genome
        genome_assembly[info.id] = assembly
        #print(info.id, info.type)

100%|██████████| 1298/1298 [02:23<00:00,  9.03it/s]

In [5]:
_taxonomy = {}
_taxonomy.update(pd.read_csv('gtdb_table_arc.csv', index_col=0).to_dict()['Classification'])
_taxonomy.update(pd.read_csv('gtdb_table_bac.csv', index_col=0).to_dict()['Classification'])
genome_taxa = {}
for genome_id in genomes:
    genome_taxa[genome_id] = _taxonomy[(genome_assembly[genome_id].info.id)]

In [6]:
for genome_id in genome_taxa:
    taxa = genome_taxa[genome_id]
    _taxa_parts = taxa.split(';')
    if _taxa_parts[0] == 'd__Archaea':
        if 'f__Haloarculaceae' in taxa:
            print(taxa)

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__CBA1134;s__CBA1134 sp009184545
d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__
d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Natronomonas;s__
d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__
d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__
d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Natronomonas;s__

In [63]:
models = {}
for genome_id in genome_taxa:
    taxa = genome_taxa[genome_id]
    _taxa_parts = taxa.split(';')
    if 'c__Halanaerobiia' in taxa:
        models[genome_id] = cobra.io.read_sbml_model(f'./data/models/base/{genome_id}.xml')
        print(taxa)

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__CBA1134;s__CBA1134 sp009184545

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Natronomonas;s__

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Halomicroarcula;s__

ERROR:cobra.io.sbml:'' is not a valid SBML 'SId'.

d__Archaea;p__Halobacteriota;c__Halobacteria;o__Halobacteriales;f__Haloarculaceae;g__Natronomonas;s__

In [93]:
model_genomes = {}
for genome_id in genome_taxa:
    taxa = genome_taxa[genome_id]
    _taxa_parts = taxa.split(';')
    if 'f__Rhodobacteraceae' in taxa:
        model_genomes[genome_id] = genomes[genome_id]
        #models[genome_id] = cobra.io.read_sbml_model(f'./data/models/base/{genome_id}.xml')
        #print(taxa)

In [94]:
import pymongo
from modelseedpy_ext.re.hash_seq import HashSeq
mongo = pymongo.MongoClient('mongodb://sequoia.mcs.anl.gov:27017')
c_protein_to_rast = mongo['database']['protein_to_rast']
missing = {}
feature_genome_count = {}
genome_arr = list(model_genomes)
for genome_id in tqdm(genome_arr):
    genome = genomes[genome_id]
    for feature in genome.features:
        h = HashSeq(feature.seq)
        doc = c_protein_to_rast.find_one({'_id': h.hash_value})
        if doc:
            annotations_rast = doc['value']
            if annotations_rast:
                for annotation_rast in annotations_rast:
                    if annotation_rast not in feature_genome_count:
                        feature_genome_count[annotation_rast] = {genome_id: 0 for genome_id in genome_arr}
                    feature_genome_count[annotation_rast][genome_id] += 1
        else:
            missing[(genome_id, feature.id)] = feature
            #print(f'missing annotation {feature.id}')

100%|██████████| 25/25 [00:56<00:00,  2.26s/it]

In [95]:
pd.DataFrame(feature_genome_count).transpose().to_csv('./data/f__Rhodobacteraceae.rast.tsv', sep='\t')

In [84]:
all_feature_genome_count = feature_genome_count

In [103]:
for f in all_feature_genome_count:
    if 'coenzyme m' in f.lower():
        print(f)
        for g, v in all_feature_genome_count[f].items():
            if v != 0:
                print('\t', v, '\t', genome_taxa[g])

Methyl coenzyme M reductase system component A2
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
[Methyl-Co(III) methylamine-specific corrinoid protein]:coenzyme M methyltransferase (EC 2.1.1.247)
	 2 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase system component A2 homolog
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methylcobalamin:coenzyme M methyltransferase MA0779
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase gamma subunit (EC 2.8.4.1)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase alpha subunit (EC 2.8.4.1)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase associated protein
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase beta subunit (EC 2.8.4.1)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase operon protein D
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
Methyl coenzyme M reductase operon protein C
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit H (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
	 1 	 d__Bacteria;p__Desulfobacterota;c__Desulfobacteria;o__Desulfatiglandales;f__Desulfatiglandaceae;g__NaphS2;s__
	 1 	 d__Bacteria;p__Desulfobacterota;c__Desulfovibrionia;o__Desulfovibrionales;f__Desulfohalobiaceae;g__;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit G (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit F (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit A (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit C (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit D (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit E (EC 2.1.1.86)
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
N5-methyltetrahydromethanopterin:coenzyme M methyltransferase subunit X
	 1 	 d__Archaea;p__Halobacteriota;c__Methanosarcinia;o__Methanosarcinales;f__Methanosarcinaceae;g__Methanolobus;s__
putative epoxyalkane:coenzyme M transferase
	 1 	 d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__;f__;g__;s__
	 1 	 d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Nitrincolaceae;g__Marinobacterium;s__Marinobacterium sp013373575

In [50]:
def crop_ast(seq):
    if seq[-1] == '*':
        return seq[:-1]
    return seq
h_seq = {}
for feature in missing.values():
    seq = crop_ast(feature.seq)
    h = HashSeq(seq).hash_value
    if h not in h_seq:
        h_seq[h] = seq

In [52]:
def chunk_dict(data, c_protein_to_rast, chunk_size):
    """Yield successive chunks of size chunk_size from a dictionary."""
    payload = []
    for k, v in data.items():
        doc = c_protein_to_rast.find_one({'_id': k})
        if doc is None:
            payload.append(MSFeature(k, v))
            if len(payload) >= chunk_size:
                yield payload
                payload = []
        else:
            #print(doc)
            pass
    if len(payload) > 0:
        yield payload

In [54]:
from modelseedpy.core.msgenome import MSGenome, MSFeature
from modelseedpy import RastClient
rast = RastClient()
for chunk in tqdm(chunk_dict(h_seq, c_protein_to_rast, 5000)):
    genome = MSGenome()
    genome.features += chunk
    rast.annotate_genome(genome)
    for f in genome.features:
        c_protein_to_rast.insert_one({'_id': f.id, 'value': f.ontology_terms.get('RAST')})

31it [03:25,  6.64s/it]

In [51]:
model_id = 'Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST'

'Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST'

In [54]:
modelseed = modelseedpy.biochem.from_local('/scratch/fliu/data/ModelSEEDDatabase/')

In [62]:
template_arc = kbase.get_from_ws('ArchaeaModelTemplateV5_test', 12218)

In [89]:
super_model = cobra.core.Model()
super_model_reactions = {}
for model_id in models:
    model = models[model_id]
    for r in model.reactions:
        seed_id = r.id[:-1]
        if seed_id in template_arc.reactions:
            template_reaction = template_arc.reactions.get_by_id(seed_id)
            if template_reaction.id not in super_model_reactions:
                model_reaction = template_reaction.to_reaction(model, index='0')
                super_model_reactions[model_reaction.id] = model_reaction

In [90]:
super_model.add_reactions([r for r in super_model_reactions.values()])

In [91]:
clade = 'f__Haloferacaceae'
cobra.io.save_json_model(super_model, f'./data/models/{clade}.model.base.json')

In [99]:
for model_id in models:
    model = models[model_id]
    if 'cpd01024_c0' in model.metabolites:
        print(model_id)

Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST

In [100]:
models

{'Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.contigs__.RAST': <Model  at 0x7f238836e4a0>,
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST': <Model  at 0x7f234618f670>,
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.contigs__.RAST': <Model  at 0x7f2344bc69b0>,
 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST': <Model  at 0x7f234450d780>,
 'Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST': <Model  at 0x7f23440879a0>,
 'Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST': <Model  at 0x7f2343af6800>,
 'Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST': <Model  at 0x7f234329b130>,
 'Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST': <Model  at 0x7f2342bc3a60>,
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.contigs__.RAST': <Model  at 0x7f2342569270>,
 'Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.contigs__.RAST': <Model  at 0x7f2341edece0>,
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST': <Model  at 0x7f234169fbe0>,
 'Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST': <Model  at 0x7f2340f6e350>}

In [57]:
modelseed.reactions.get_by_id()

# OLD!

In [4]:
model = kbase.get_from_ws('Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2.gf', 186678)

In [39]:
(model.reactions.EX_cpd25960_c0 *-1) + model.reactions.rxn26456_c0 + model.reactions.rxn26457_c0 + model.reactions.rxn43120_c0

In [62]:
model.add_reactions([template.reactions.rxn26447_c.to_reaction(model)])

In [58]:
model.reactions.rxn43120_c0

In [59]:
model.metabolites.cpd26508_c0

In [43]:
template = kbase.get_from_ws(model.template_ref)

In [48]:
model.reactions.SK_cpd03091_c0

In [46]:
template.drains

{<NewModelTemplateCompCompound cpd01042_c at 0x7f2ba59be710>: (0, 1000),
 <NewModelTemplateCompCompound cpd02701_c at 0x7f2ba58a87f0>: (0, 1000),
 <NewModelTemplateCompCompound cpd03091_c at 0x7f2ba5b403a0>: (0, 1000),
 <NewModelTemplateCompCompound cpd11416_c at 0x7f2ba5b41720>: (0, 1000),
 <NewModelTemplateCompCompound cpd15302_c at 0x7f2ba5a73a00>: (0, 1000),
 <NewModelTemplateCompCompound cpd22811_c at 0x7f2ba56c53c0>: (0, 1000)}

In [50]:
for r in model.metabolites.cpd03091_c0.reactions:
    print(r.id, '\t', r.build_reaction_string(True))

rxn04704_c0 	 2 S-Adenosyl-L-methionine [c0] + CoproporphyrinogenIII [c0] --> 2 CO2 [c0] + 2 L-Methionine [c0] + ProtoporphyrinogenIX [c0] + 2 5'-Deoxyadenosine [c0]
rxn40559_c0 	 S-Adenosyl-L-methionine [c0] + 13(1)-Hydroxy-Mg-protoporphyrin IX 13-monomethyl ester [c0] --> L-Methionine [c0] + 3 H+ [c0] + 5'-Deoxyadenosine [c0] + 13(1)-Oxo-Mg-protoporphyrin IX 13-monomethyl ester [c0]
rxn46959_c0 	 H2O [c0] + S-Adenosyl-L-methionine [c0] + Mg-Protoporphyrin IX 13-monomethyl ester [c0] <=> L-Methionine [c0] + H+ [c0] + 5'-Deoxyadenosine [c0] + 13(1)-Hydroxy-Mg-protoporphyrin IX 13-monomethyl ester [c0]
SK_cpd03091_c0 	 5'-Deoxyadenosine [c0] -->
rxn43120_c0 	 NADPH [c0] + S-Adenosyl-L-methionine [c0] + PRPn [c0] --> NADP [c0] + L-Methionine [c0] + Methane [c0] + 5'-Deoxyadenosine [c0] + 5-phospho-alpha-D-ribosyl 1,2-cyclic phosphate [c0]
rxn43329_c0 	 S-Adenosyl-L-methionine [c0] + 13(1)-Oxo-Mg-protoporphyrin IX 13-monomethyl ester [c0] <-- L-Methionine [c0] + 5'-Deoxyadenosine [c0] + Divinylprotochlorophyllide [c0]

In [56]:
model.objective = 'rxn43120_c0'

In [65]:
model.summary()

In [7]:
model.metabolites.cpd26519_c0

In [51]:
model.metabolites.cpd00128_c0

In [53]:
if 'cpd00128_c0' in model.metabolites and 'SK_cpd00128_c0' not in model.reactions:
    ex = Reaction('SK_cpd00128_c0', 'Sk for adenine', '', 0, 1000)
    ex.add_metabolites({
        model.metabolites.cpd00128_c0: -1
    })
    model.add_reactions([ex])
    print('!')

In [11]:
model.reactions.rxn26456_c0

In [8]:
model.reactions.rxn26457_c0

In [5]:
model.reactions.rxn43120_c0

In [2]:
ws_reg = 155805
ws_enh = 186678

In [3]:
kbase = KBaseCache(path='/scratch/fliu/data/kbase/cache')

In [98]:
model_reg = kbase.get_from_ws('Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2', ws_reg)
model_enh = kbase.get_from_ws('Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2', ws_enh)

Set parameter TSPort to value 27070
Set parameter TokenServer to value "lic-vmw-01.cels.anl.gov"

In [66]:
ws_enh2 = 188065
models_enh2 = {}
for info in kbase.list_workspace(ws_enh2):
    if info.type == 'KBaseFBA.FBAModel' and info.id.endswith('.pyr.O2'):
        models_enh2[info.id] = kbase.get_object(info.id, ws_enh2)
        print(info.id, info.type)

WARNING:cobrakbase.kbaseapi_cache:created folder(s) [/scratch/fliu/data/kbase/cache/188065]

R1_A_D2.21.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.5.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_H2O.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_H2O.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D1.31.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_H2O.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D2.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D2.9.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D2.67.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D2.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_H2O.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_H2O.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_H2O.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_H2O.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_H2O.035.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_H2O.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_H2O.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_H2O.35.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_H2O.20.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.12.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.37.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_H2O.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_H2O.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_H2O.60.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.119.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.52.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.39.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.39.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.47.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_H2O.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.78.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.21.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.53.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_H2O.5.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.23b.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.5.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_H2O.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.062.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.65.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.59.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.50.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.49.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.20.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D2.37.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.5.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.98.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D1.047.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.40.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.22.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.22.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.022.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.24.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.109.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_H2O.005.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_H2O.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D1.40.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D2.58.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D2.30.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.48.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.9.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.73.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.59.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.118.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.33.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D2.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.34.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_D2.55.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_H2O.6.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.28.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.029.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.27.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.31.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.028.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.84.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D2.85.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D2.40.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.20.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_H2O.49.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.34.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.37.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.3.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.24.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.49.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_H2O.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.7b.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.32.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.20.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_H2O.34.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.55.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.57.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.37.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.42.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.46.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D2.54.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.42.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.23.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_H2O.79.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.27.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.009.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.10b.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.54.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D1.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_H2O.2.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.24.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.27.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.124.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.66.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.22.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.6.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.38.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.37.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.21.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.27.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.38.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.28.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.12.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.41.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.41.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.21.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.52.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.62.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.014.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.7.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D2.36.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D1.110.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.7.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.47.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.037.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.61.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.50.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D2.47.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.46.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.36.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.55.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_D2.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.20.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.50.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.32.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_H2O.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.84.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.15.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.88.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_H2O.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.86.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.40.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.32.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_D1.44.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.2.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D2.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.35.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.104.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.29.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.38.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.80.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.15.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.93.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.28.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.42.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D1.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.91.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.34.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.1.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.120.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D1.22.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D1.27.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.43.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.26.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.71.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.9.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_H2O.67.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.31.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.15.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.69.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.78.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_H2O.67.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.143.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.23.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.33.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.12.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.30.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.18.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.26.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D1.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D1.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.87.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.63.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.68.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.44.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.7.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.59.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.98.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.2.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_D2.42.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.8.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_H2O.022.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.9.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.7.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D2.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.7.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_D1.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.6.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.32.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.42.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D1.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.49.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_H2O.28.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.11.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.15.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.89.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D2.100.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.26.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.37b.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.89.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.45.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.39.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D1.13.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D2.28.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_C_H2O.23.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_D1.9.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_C_D1.95.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.10.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.80.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_A_D1.23.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_C_black.51.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D1.44.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.36.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.49.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_DShore.40.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_C_D2.25.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.38.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.58.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_A_D1.001.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_C_D2.4.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_A_D2.50.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_D1.16.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_H2O.62.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.52.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_H2O.44.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R1_B_H2O.19.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_B_D2.43.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_H2O.017.pg.G.D.pyr.O2 KBaseFBA.FBAModel
SF2_B_H2O.14.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2_restored_H2O.002.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_D2.6.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_A_D1.17.pg.G.D.pyr.O2 KBaseFBA.FBAModel
R2A_B_H2O.69.pg.G.D.pyr.O2 KBaseFBA.FBAModel

In [4]:
models_reg = {}
for info in kbase.list_workspace(ws_reg):
    if info.type == 'KBaseFBA.FBAModel' and info.id.endswith('.pyr.O2'):
        models_reg[info.id] = kbase.get_object(info.id, ws_reg)
        print(info.id, info.type)

Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.39.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.119.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.39.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.78.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.23.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.53.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.65.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_maxbin.062.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.50.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.98.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_maxbin.047.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.45.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.005.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_maxbin.022.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.109.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.30.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.58.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_maxbin.035.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.9.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.33.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.6.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.18.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.28.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_maxbin.028.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.34.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.3.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.62.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_maxbin.029.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.20.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.43.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.54.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.44.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.23.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_concoct_out.2.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.13.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.24.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.017.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.124.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.22.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.69.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.6.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.66.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.28.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.62.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_maxbin.014.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_maxbin.009.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.110.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_maxbin.037.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.7.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.47.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.54.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D1_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.41.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.84.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.61.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.8.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.32.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.104.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.15.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.15.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.86.contigs__.RAST.pyr.O2 KBaseFBA.FBAModel

In [5]:
models_enh = {}
for info in kbase.list_workspace(ws_enh):
    if info.type == 'KBaseFBA.FBAModel' and info.id.endswith('.pyr.O2'):
        models_enh[info.id] = kbase.get_object(info.id, ws_enh)
        print(info.id, info.type)

Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.11.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.20.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_maxbin.035.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.52.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.50.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.62.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.69.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_maxbin.029.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.43.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.44.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.49.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.017.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.34.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.24.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.4.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.54.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D1_MG_DASTool_bins_concoct_out.4.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.37.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_maxbin.009.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.36.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.41.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.61.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.46.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.32.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.46.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.50.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.15.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_concoct_out.44.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.86.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.25.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.2.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.38.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.18.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.13.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.80.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.4.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.17.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.28.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.91.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.34.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.120.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.1.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.22.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.26.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.27.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.43.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.9.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.71.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.31.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_metabat.6.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.15.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.69.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.78.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.23.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.12.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.67.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.87.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.33.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.30.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.26.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.44.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.68.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.63.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.98.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.59.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.2.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.42.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.14.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.13.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.8.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.9.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_maxbin.022.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_concoct_out.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.7.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.16.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.6.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_metabat.42.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.100.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.11.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D1_MG_DASTool_bins_concoct_out.13.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.49.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.28.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.89.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.15.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.37.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.39.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.89.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.25.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.26.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_metabat.13.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.23.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_D1_MG_DASTool_bins_metabat.9.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.51.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.80.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_D1_MG_DASTool_bins_concoct_out.23.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.10.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.44.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.49.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.58.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.11.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.4.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.36.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.119.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.39.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.39.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.78.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.5.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.23.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.29.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.53.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.45.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.pangenome.RAST.glm4ec.pyr.O2 KBaseFBA.FBAModel

In [ ]:
for info in kbase.list_workspace(ws_enh):
    if info.type == 'KBaseFBA.FBAModel':
        kbase.get_from_ws(info.id, ws_enh)
        print(info.id, info.type)

In [78]:
import pandas as pd
mapping = pd.read_csv('./mag_name_mapping.tsv', header=None, sep='\t', index_col=0).to_dict()[1]

In [35]:
templates = {}

In [38]:
for k in templates:
    print(templates[k].info.id)

template_v6gn_methylphosphonate_deg
template_v6gn_methylphosphonate_deg
ArchaeaTemplateV5
template_v6gp_methylphosphonate_deg
template_v6gp_methylphosphonate_deg

In [96]:
bad_mapping

{'Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.8.contigs__.RAST.pyr.O2': AttributeError("'float' object has no attribute 'replace'")}

In [95]:
bad_mapping = {}
for k in models_reg:
    try:
        model_reg = models_reg[k]
        model_enh = models_enh2.get(mapping[k].replace('.pg.', '.pg.G.D.'))
        if model_enh is not None:
            model_reg_template = model_reg['template_ref']
            if model_reg_template not in templates:
                templates[model_reg_template] = kbase.get_from_ws(model_reg_template)
            model_enh_template = model_enh['template_ref']
            if model_enh_template not in templates:
                templates[model_enh_template] = kbase.get_from_ws(model_enh_template)
            reg_gapfill = _get_gapfilled_reactions(model_reg, templates[model_reg['template_ref']])
            enh_gapfill = _get_gapfilled_reactions(model_enh, templates[model_enh['template_ref']])
            d = [k, len(model_reg['modelreactions']), len(model_enh['modelreactions']), len(reg_gapfill), len(enh_gapfill), len(_get_all_genes(model_reg)), len(_get_all_genes(model_enh))]
            print('\t'.join([str(x) for x in d]))
    except Exception as ex:
        bad_mapping[k] = ex

Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	957	957	71	38	1165	885
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.contigs__.RAST.pyr.O2	831	831	110	72	1141	980
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	679	679	86	62	957	687
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	677	677	126	104	814	507
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.39.contigs__.RAST.pyr.O2	1174	1174	60	45	1585	1039
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.119.contigs__.RAST.pyr.O2	918	918	167	134	1046	755
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	981	981	58	40	1549	1193
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.39.contigs__.RAST.pyr.O2	871	871	159	126	847	541
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2	1210	1210	69	45	2361	1794
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.78.contigs__.RAST.pyr.O2	878	878	123	84	1052	896
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.23.contigs__.RAST.pyr.O2	1041	1041	67	49	1227	1192
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1204	1204	64	39	2074	1794
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	798	798	83	58	1053	805
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1216	1216	49	36	2032	2013
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	886	886	126	101	1059	660
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	722	722	125	93	836	600
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1085	1085	49	41	1354	800
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.53.contigs__.RAST.pyr.O2	1099	1099	98	75	1195	908
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2	794	794	101	77	1187	757
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2	793	793	169	133	763	552
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	792	792	102	62	989	792
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.65.contigs__.RAST.pyr.O2	1253	1253	64	46	1750	1280
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_maxbin.062.contigs__.RAST.pyr.O2	962	962	122	62	1340	1044
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2	1227	1227	82	66	1639	908
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	682	682	109	86	793	494
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.50.contigs__.RAST.pyr.O2	903	903	116	58	1073	766
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2	864	864	136	114	873	609
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	1222	1222	90	71	1568	1034
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2	1086	1086	135	85	1551	1331
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2	705	705	121	88	1019	774
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2	1180	1180	72	41	1575	1056
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.contigs__.RAST.pyr.O2	811	811	110	79	917	581
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	1018	1018	94	71	1200	687
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2	939	939	156	88	1164	1302
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1203	1203	55	32	1674	1354
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.contigs__.RAST.pyr.O2	739	739	95	70	906	545
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	761	761	97	66	1015	772
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	851	851	82	61	1087	860
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	973	973	76	64	1233	669
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.98.contigs__.RAST.pyr.O2	911	911	118	101	1160	713
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	1215	1215	74	53	1510	904
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_maxbin.047.contigs__.RAST.pyr.O2	814	814	139	94	1303	909
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	826	826	98	74	1208	804
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2	972	972	153	80	1428	1589
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.contigs__.RAST.pyr.O2	779	779	88	68	1123	714
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.45.contigs__.RAST.pyr.O2	965	965	116	68	1406	1248
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.005.contigs__.RAST.pyr.O2	1061	1061	59	43	1763	1436
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2	1026	1026	73	49	1395	1090
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_maxbin.022.contigs__.RAST.pyr.O2	1080	1080	87	48	1689	1546
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.109.contigs__.RAST.pyr.O2	1064	1064	77	57	1510	1085
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2	1191	1191	77	58	1588	931
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2	756	756	94	71	1153	868
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	1042	1042	68	60	1291	701
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2	1005	1005	137	65	1752	1856
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	1106	1106	75	58	1611	1108
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.30.contigs__.RAST.pyr.O2	1083	1083	107	72	1169	777
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.pyr.O2	1050	1050	135	82	1392	1527
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	910	910	104	70	1286	866
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.58.contigs__.RAST.pyr.O2	521	521	344	311	261	204
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2	1056	1056	103	80	1619	1330
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_maxbin.035.contigs__.RAST.pyr.O2	419	419	248	234	200	121
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.contigs__.RAST.pyr.O2	977	977	144	123	1202	676
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.9.contigs__.RAST.pyr.O2	999	999	182	122	1106	1146
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2	1152	1152	66	47	1660	1023
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.33.contigs__.RAST.pyr.O2	1048	1048	75	37	1655	1309
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	696	696	99	78	1006	664
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.6.contigs__.RAST.pyr.O2	910	910	111	66	1035	683
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.18.contigs__.RAST.pyr.O2	1092	1092	99	78	1292	1008
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	833	833	89	70	1054	689
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2	1090	1090	81	46	1533	1006
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	1052	1052	92	63	1350	947
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.28.contigs__.RAST.pyr.O2	1057	1057	76	56	1546	1523
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	776	776	107	85	1053	718
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_maxbin.028.contigs__.RAST.pyr.O2	847	847	94	63	1209	766
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1238	1238	88	52	1950	2009
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2	993	993	94	71	1246	840
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.contigs__.RAST.pyr.O2	817	817	87	66	1049	681
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.contigs__.RAST.pyr.O2	844	844	88	66	1286	889
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2	879	879	122	76	1052	760
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.contigs__.RAST.pyr.O2	1034	1034	79	42	1454	1312
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	470	470	267	250	217	150
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	651	651	120	70	863	664
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	1007	1007	65	41	1247	766
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs__.RAST.pyr.O2	1184	1184	65	48	1910	1755
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	1147	1147	93	44	1538	1355
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.34.contigs__.RAST.pyr.O2	935	935	67	46	1194	850
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2	1040	1040	83	65	1259	760
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	763	763	110	71	1003	809
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	823	823	87	58	1251	970
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2	862	862	146	119	850	487
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.3.contigs__.RAST.pyr.O2	1212	1212	54	29	1975	1465
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2	1105	1105	118	63	1404	1243
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	600	600	143	107	693	514
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	431	431	263	248	205	131
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	830	830	100	58	1272	989
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	1066	1066	70	51	1456	1001
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2	860	860	123	96	1011	816
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.contigs__.RAST.pyr.O2	929	929	175	135	1056	1008
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2	1070	1070	61	38	1394	978
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.62.contigs__.RAST.pyr.O2	879	879	121	99	1154	968
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1115	1115	66	39	1630	1361
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	1151	1151	45	29	1721	1257
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.contigs__.RAST.pyr.O2	966	966	113	73	1316	1214
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.contigs__.RAST.pyr.O2	972	972	129	105	1272	943
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.contigs__.RAST.pyr.O2	875	875	111	81	1069	783
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.8.contigs__.RAST.pyr.O2	1034	1034	136	101	1212	788
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.contigs__.RAST.pyr.O2	897	897	118	94	1109	859
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2	619	619	124	107	768	541
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2	906	906	135	90	962	729
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1146	1146	78	60	1638	1060
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1036	1036	85	65	1284	987
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_maxbin.029.contigs__.RAST.pyr.O2	855	855	105	87	1239	1004
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2	911	911	142	125	1063	658
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.20.contigs__.RAST.pyr.O2	1056	1056	88	68	1315	717
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.43.contigs__.RAST.pyr.O2	1005	1005	91	58	1605	1609
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2	1189	1189	63	39	1827	1985
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.contigs__.RAST.pyr.O2	942	942	114	84	1204	834
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	1142	1142	80	54	1294	1184
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.54.contigs__.RAST.pyr.O2	1018	1018	97	60	1271	922
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1070	1070	89	59	1647	1258
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.contigs__.RAST.pyr.O2	1010	1010	142	109	1257	954
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	1097	1097	72	55	1319	796
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1197	1197	69	53	1732	953
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	1007	1007	76	58	1348	762
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2	971	971	86	57	1337	955
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.44.contigs__.RAST.pyr.O2	956	956	88	73	1226	861
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs__.RAST.pyr.O2	1186	1186	62	48	1794	1327
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.contigs__.RAST.pyr.O2	838	838	108	83	983	903
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.23.contigs__.RAST.pyr.O2	948	948	121	72	1210	1086
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_concoct_out.2.contigs__.RAST.pyr.O2	952	952	90	67	1104	730
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2	862	862	129	94	966	889
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.13.contigs__.RAST.pyr.O2	1025	1025	124	63	1544	1072
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.24.contigs__.RAST.pyr.O2	928	928	124	103	1041	565
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	927	927	141	113	1087	712
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.pyr.O2	1061	1061	105	64	1571	1282
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2	872	872	97	79	983	620
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.017.contigs__.RAST.pyr.O2	903	903	113	77	1239	1206
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.124.contigs__.RAST.pyr.O2	1065	1065	50	33	1551	1026
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2	837	837	147	100	907	1028
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2	1115	1115	88	61	1709	1095
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.22.contigs__.RAST.pyr.O2	883	883	72	53	1107	849
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.contigs__.RAST.pyr.O2	1051	1051	108	51	1112	956
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.69.contigs__.RAST.pyr.O2	832	832	125	93	962	722
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.6.contigs__.RAST.pyr.O2	1226	1226	74	57	2130	1165
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.contigs__.RAST.pyr.O2	1012	1012	87	60	1431	923
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.66.contigs__.RAST.pyr.O2	818	818	165	136	801	522
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2	1027	1027	99	71	1335	1042
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	1084	1084	95	62	1321	1462
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2	1033	1033	68	44	1589	1206
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	920	920	149	117	1022	701
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1054	1054	121	55	1142	1192
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.28.contigs__.RAST.pyr.O2	970	970	120	98	1028	593
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.62.contigs__.RAST.pyr.O2	917	917	101	84	1044	595
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_maxbin.014.contigs__.RAST.pyr.O2	1127	1127	50	36	1566	901
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_maxbin.009.contigs__.RAST.pyr.O2	1089	1089	89	68	1420	1197
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.110.contigs__.RAST.pyr.O2	1168	1168	56	33	1597	1113
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	926	926	101	78	1025	669
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2	1092	1092	120	70	1521	1455
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.pyr.O2	957	957	72	35	1210	1043
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_maxbin.037.contigs__.RAST.pyr.O2	1124	1124	87	65	1789	983
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2	1032	1032	72	45	1390	1150
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.7.contigs__.RAST.pyr.O2	1131	1131	74	55	1412	778
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.47.contigs__.RAST.pyr.O2	970	970	129	102	1180	759
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	886	886	96	62	1205	1240
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2	1064	1064	107	85	1317	722
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	825	825	97	64	1133	1038
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	964	964	89	68	1133	618
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.54.contigs__.RAST.pyr.O2	947	947	83	57	1321	977
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	1244	1244	59	37	2099	2156
Salt_Pond_MetaG_R2A_B_D1_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2	1034	1034	94	59	1435	1383
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1108	1108	86	68	1340	730
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2	1145	1145	67	54	1603	877
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.contigs__.RAST.pyr.O2	1122	1122	106	79	1598	1093
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	1223	1223	96	77	1735	1197
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2	971	971	131	65	1412	1433
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2	950	950	59	41	1128	619
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2	856	856	140	120	837	562
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2	1165	1165	74	47	1460	998
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1200	1200	78	52	1624	1072
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2	932	932	150	129	1051	581
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.41.contigs__.RAST.pyr.O2	1100	1100	87	66	1398	1127
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2	1112	1112	87	39	1625	1324
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	1098	1098	83	44	1335	1331
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2	1133	1133	71	53	1684	1110
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2	1287	1287	65	47	2277	1559
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2	1015	1015	81	55	1484	917
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1009	1009	129	91	1075	720
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2	1082	1082	84	55	1562	977
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.84.contigs__.RAST.pyr.O2	458	458	309	214	262	351
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.61.contigs__.RAST.pyr.O2	953	953	168	144	1018	590
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1157	1157	68	46	1765	1299
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2	1079	1079	65	40	1607	1516
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2	989	989	110	63	1350	993
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2	1126	1126	109	83	1596	924
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2	1169	1169	82	71	1658	1114
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1170	1170	90	67	1585	1109

In [62]:
for k in models_reg:
    model_reg = models_reg[k]
    model_enh = models_enh[k.split('contigs__')[0] + 'pangenome.RAST.glm4ec.pyr.O2']
    model_reg_template = model_reg['template_ref']
    if model_reg_template not in templates:
        templates[model_reg_template] = kbase.get_from_ws(model_reg_template)
    model_enh_template = model_enh['template_ref']
    if model_enh_template not in templates:
        templates[model_enh_template] = kbase.get_from_ws(model_enh_template)
    reg_gapfill = _get_gapfilled_reactions(model_reg, templates[model_reg['template_ref']])
    enh_gapfill = _get_gapfilled_reactions(model_enh, templates[model_enh['template_ref']])
    d = [k, len(model_reg['modelreactions']), len(model_enh['modelreactions']), len(reg_gapfill), len(enh_gapfill), len(_get_all_genes(model_reg)), len(_get_all_genes(model_enh))]
    print('\t'.join([str(x) for x in d]))

Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	957	972	71	54	1165	1247
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.5.contigs__.RAST.pyr.O2	831	840	110	93	1141	1252
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	679	686	86	68	957	1046
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	677	684	126	108	814	909
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.39.contigs__.RAST.pyr.O2	1174	1187	60	54	1585	1697
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.119.contigs__.RAST.pyr.O2	918	935	167	141	1046	1194
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	981	996	58	49	1549	1640
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.39.contigs__.RAST.pyr.O2	871	877	159	150	847	887
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2	1210	1218	69	54	2361	2603
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.78.contigs__.RAST.pyr.O2	878	893	123	105	1052	1139
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.23.contigs__.RAST.pyr.O2	1041	1054	67	61	1227	1349
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1204	1212	64	50	2074	2307
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	798	810	83	64	1053	1162
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1216	1220	49	37	2032	2238
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	886	892	126	110	1059	1135
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	722	743	125	111	836	929
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1085	1107	49	52	1354	1449
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.53.contigs__.RAST.pyr.O2	1099	1112	98	84	1195	1267
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2	794	803	101	88	1187	1306
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2	793	798	169	149	763	815
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	792	802	102	86	989	1063
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.65.contigs__.RAST.pyr.O2	1253	1269	64	45	1750	1943
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_maxbin.062.contigs__.RAST.pyr.O2	962	973	122	98	1340	1483
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2	1227	1235	82	70	1639	1781
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	682	699	109	99	793	872
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.50.contigs__.RAST.pyr.O2	903	916	116	96	1073	1160
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2	864	868	136	118	873	930
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	1222	1222	90	65	1568	1694
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2	1086	1104	135	119	1551	1716
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2	705	718	121	99	1019	1122
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.25.contigs__.RAST.pyr.O2	1180	1192	72	61	1575	1695
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.9.contigs__.RAST.pyr.O2	811	827	110	93	917	1021
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	1018	1030	94	74	1200	1291
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2	939	955	156	133	1164	1287
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.5.contigs__.RAST.pyr.O2	1203	1211	55	41	1674	1831
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_concoct_out.67.contigs__.RAST.pyr.O2	739	749	95	78	906	1010
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	761	770	97	80	1015	1137
Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	851	871	82	67	1087	1211
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	973	991	76	63	1233	1305
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.98.contigs__.RAST.pyr.O2	911	916	118	104	1160	1250
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	1215	1221	74	55	1510	1630
Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_maxbin.047.contigs__.RAST.pyr.O2	814	821	139	114	1303	1401
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	826	837	98	83	1208	1330
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2	972	987	153	120	1428	1604
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.29.contigs__.RAST.pyr.O2	779	791	88	74	1123	1259
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.45.contigs__.RAST.pyr.O2	965	968	116	99	1406	1564
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.005.contigs__.RAST.pyr.O2	1061	1080	59	55	1763	1948
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.22.contigs__.RAST.pyr.O2	1026	1030	73	56	1395	1508
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_maxbin.022.contigs__.RAST.pyr.O2	1080	1085	87	59	1689	1896
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.109.contigs__.RAST.pyr.O2	1064	1077	77	63	1510	1614
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2	1191	1201	77	58	1588	1721
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_concoct_out.45.contigs__.RAST.pyr.O2	756	767	94	80	1153	1279
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	1042	1046	68	52	1291	1369
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2	1005	1015	137	116	1752	1974
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	1106	1114	75	62	1611	1713
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.30.contigs__.RAST.pyr.O2	1083	1090	107	93	1169	1242
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.19.contigs__.RAST.pyr.O2	1050	1056	135	112	1392	1561
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	910	925	104	86	1286	1372
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.58.contigs__.RAST.pyr.O2	521	528	344	339	261	278
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_concoct_out.59.contigs__.RAST.pyr.O2	1056	1059	103	87	1619	1803
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_maxbin.035.contigs__.RAST.pyr.O2	419	416	248	234	200	217
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.118.contigs__.RAST.pyr.O2	977	1022	144	135	1202	1319
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.9.contigs__.RAST.pyr.O2	999	999	182	140	1106	1201
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2	1152	1163	66	52	1660	1793
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.33.contigs__.RAST.pyr.O2	1048	1064	75	56	1655	1794
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	696	709	99	79	1006	1095
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_metabat.6.contigs__.RAST.pyr.O2	910	920	111	100	1035	1104
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.18.contigs__.RAST.pyr.O2	1092	1106	99	87	1292	1387
Salt_Pond_MetaG_R2_A_H2O_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	833	859	89	74	1054	1141
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2	1090	1101	81	60	1533	1674
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.11.contigs__.RAST.pyr.O2	1052	1058	92	64	1350	1462
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.28.contigs__.RAST.pyr.O2	1057	1076	76	63	1546	1691
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	776	787	107	89	1053	1159
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_maxbin.028.contigs__.RAST.pyr.O2	847	852	94	79	1209	1292
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1238	1244	88	65	1950	2197
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2	993	1008	94	76	1246	1337
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.35.contigs__.RAST.pyr.O2	817	834	87	73	1049	1178
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_concoct_out.60.contigs__.RAST.pyr.O2	844	858	88	68	1286	1442
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.31.contigs__.RAST.pyr.O2	879	886	122	100	1052	1140
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.84.contigs__.RAST.pyr.O2	1034	1043	79	57	1454	1595
Salt_Pond_MetaG_R2_B_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	470	468	267	241	217	240
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	651	659	120	98	863	956
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_metabat.20.contigs__.RAST.pyr.O2	1007	1017	65	53	1247	1333
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs__.RAST.pyr.O2	1184	1201	65	53	1910	2111
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	1147	1159	93	75	1538	1722
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_metabat.34.contigs__.RAST.pyr.O2	935	938	67	57	1194	1258
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2	1040	1048	83	64	1259	1352
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	763	780	110	97	1003	1097
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.40.contigs__.RAST.pyr.O2	823	834	87	74	1251	1390
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2	862	874	146	117	850	940
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.3.contigs__.RAST.pyr.O2	1212	1218	54	37	1975	2206
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2	1105	1113	118	96	1404	1525
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	600	614	143	119	693	752
Salt_Pond_MetaG_R2_C_H2O_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	431	447	263	257	205	227
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	830	842	100	83	1272	1435
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	1066	1072	70	53	1456	1569
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2	860	865	123	103	1011	1089
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.48.contigs__.RAST.pyr.O2	929	930	175	146	1056	1157
Salt_Pond_MetaG_R2A_C_H2O_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2	1070	1060	61	52	1394	1524
Salt_Pond_MetaG_R2A_A_H2O_MG_DASTool_bins_concoct_out.62.contigs__.RAST.pyr.O2	879	883	121	115	1154	1225
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1115	1124	66	47	1630	1760
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_metabat.11.contigs__.RAST.pyr.O2	1151	1167	45	33	1721	1894
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.73.contigs__.RAST.pyr.O2	966	977	113	100	1316	1470
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.52.contigs__.RAST.pyr.O2	972	974	129	110	1272	1404
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_maxbin.001.contigs__.RAST.pyr.O2	875	881	111	100	1069	1139
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.8.contigs__.RAST.pyr.O2	1034	1028	136	92	1212	1312
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.51.contigs__.RAST.pyr.O2	897	901	118	99	1109	1202
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2	619	639	124	106	768	834
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.51.contigs__.RAST.pyr.O2	906	916	135	120	962	1039
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1146	1169	78	63	1638	1781
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1036	1051	85	68	1284	1426
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_maxbin.029.contigs__.RAST.pyr.O2	855	857	105	93	1239	1321
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2	911	939	142	140	1063	1183
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.20.contigs__.RAST.pyr.O2	1056	1067	88	70	1315	1403
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.43.contigs__.RAST.pyr.O2	1005	1010	91	77	1605	1757
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2	1189	1186	63	45	1827	2031
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.002.contigs__.RAST.pyr.O2	942	951	114	94	1204	1308
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.14.contigs__.RAST.pyr.O2	1142	1158	80	67	1294	1391
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.54.contigs__.RAST.pyr.O2	1018	1029	97	80	1271	1362
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1070	1086	89	65	1647	1817
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.85.contigs__.RAST.pyr.O2	1010	1031	142	117	1257	1380
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.29.contigs__.RAST.pyr.O2	1097	1107	72	54	1319	1427
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1197	1208	69	54	1732	1880
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	1007	1025	76	59	1348	1476
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2	971	981	86	68	1337	1459
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.44.contigs__.RAST.pyr.O2	956	960	88	74	1226	1339
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs__.RAST.pyr.O2	1186	1182	62	41	1794	1957
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_concoct_out.14.contigs__.RAST.pyr.O2	838	838	108	89	983	1040
Salt_Pond_MetaGSF2_A_H2O_MG_DASTool_bins_concoct_out.23.contigs__.RAST.pyr.O2	948	949	121	97	1210	1318
Salt_Pond_MetaG_R1_A_H2O_MG_DASTool_bins_concoct_out.2.contigs__.RAST.pyr.O2	952	961	90	73	1104	1186
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.49.contigs__.RAST.pyr.O2	862	864	129	115	966	1033
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.13.contigs__.RAST.pyr.O2	1025	1039	124	102	1544	1663
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.24.contigs__.RAST.pyr.O2	928	944	124	103	1041	1113
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	927	932	141	117	1087	1177
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs__.RAST.pyr.O2	1061	1073	105	95	1571	1729
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.19.contigs__.RAST.pyr.O2	872	874	97	81	983	1047
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_maxbin.017.contigs__.RAST.pyr.O2	903	910	113	99	1239	1347
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.124.contigs__.RAST.pyr.O2	1065	1076	50	34	1551	1658
Salt_Pond_MetaG_R2_restored_H2O_MG_DASTool_bins_concoct_out.34.contigs__.RAST.pyr.O2	837	861	147	145	907	978
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2	1115	1125	88	66	1709	1838
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_concoct_out.22.contigs__.RAST.pyr.O2	883	905	72	74	1107	1186
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.38.contigs__.RAST.pyr.O2	1051	1053	108	81	1112	1198
Salt_Pond_MetaG_R2A_B_H2O_MG_DASTool_bins_concoct_out.69.contigs__.RAST.pyr.O2	832	843	125	110	962	1029
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.6.contigs__.RAST.pyr.O2	1226	1238	74	57	2130	2297
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.57.contigs__.RAST.pyr.O2	1012	1033	87	77	1431	1505
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.66.contigs__.RAST.pyr.O2	818	828	165	147	801	863
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.24.contigs__.RAST.pyr.O2	1027	1021	99	65	1335	1430
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	1084	1098	95	79	1321	1434
Salt_Pond_MetaGSF2_C_D2_MG_DASTool_bins_concoct_out.42.contigs__.RAST.pyr.O2	1033	1043	68	54	1589	1733
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_concoct_out.25.contigs__.RAST.pyr.O2	920	924	149	128	1022	1138
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1054	1063	121	97	1142	1246
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.28.contigs__.RAST.pyr.O2	970	977	120	98	1028	1095
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.62.contigs__.RAST.pyr.O2	917	924	101	85	1044	1148
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_maxbin.014.contigs__.RAST.pyr.O2	1127	1139	50	45	1566	1686
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_maxbin.009.contigs__.RAST.pyr.O2	1089	1102	89	66	1420	1553
Salt_Pond_MetaG_R2_B_D1_MG_DASTool_bins_concoct_out.110.contigs__.RAST.pyr.O2	1168	1178	56	42	1597	1736
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	926	945	101	83	1025	1109
Salt_Pond_MetaG_R2A_A_D1_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2	1092	1106	120	96	1521	1689
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.pyr.O2	957	973	72	64	1210	1297
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_maxbin.037.contigs__.RAST.pyr.O2	1124	1126	87	64	1789	1920
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.50.contigs__.RAST.pyr.O2	1032	1036	72	53	1390	1493
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.7.contigs__.RAST.pyr.O2	1131	1160	74	61	1412	1527
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.metabat.47.contigs__.RAST.pyr.O2	970	986	129	111	1180	1303
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.37.contigs__.RAST.pyr.O2	886	894	96	78	1205	1307
Salt_Pond_MetaG_R2A_B_D2_MG_DASTool_bins_concoct_out.47.contigs__.RAST.pyr.O2	1064	1075	107	86	1317	1427
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	825	828	97	75	1133	1215
Salt_Pond_MetaG_R2A_C_D1_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	964	978	89	70	1133	1211
Salt_Pond_MetaG_R1_A_D1_MG_DASTool_bins.concoct_out.54.contigs__.RAST.pyr.O2	947	957	83	72	1321	1397
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs__.RAST.pyr.O2	1244	1250	59	40	2099	2329
Salt_Pond_MetaG_R2A_B_D1_MG_DASTool_bins_concoct_out.4.contigs__.RAST.pyr.O2	1034	1060	94	76	1435	1545
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs__.RAST.pyr.O2	1108	1122	86	72	1340	1434
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_metabat.7.contigs__.RAST.pyr.O2	1145	1154	67	53	1603	1725
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.41.contigs__.RAST.pyr.O2	1122	1164	106	71	1598	1796
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.21.contigs__.RAST.pyr.O2	1223	1236	96	69	1735	1972
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.16.contigs__.RAST.pyr.O2	971	974	131	105	1412	1537
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.12.contigs__.RAST.pyr.O2	950	961	59	41	1128	1218
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.52.contigs__.RAST.pyr.O2	856	862	140	124	837	923
Salt_Pond_MetaGSF2_B_D2_MG_DASTool_bins_metabat.4.contigs__.RAST.pyr.O2	1165	1191	74	71	1460	1577
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.16.contigs__.RAST.pyr.O2	1200	1225	78	61	1624	1760
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2	932	940	150	130	1051	1140
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.41.contigs__.RAST.pyr.O2	1100	1106	87	71	1398	1560
Salt_Pond_MetaGSF2_A_D2_MG_DASTool_bins_concoct_out.55.contigs__.RAST.pyr.O2	1112	1123	87	70	1625	1764
Salt_Pond_MetaG_R2A_A_D2_MG_DASTool_bins_concoct_out.10.contigs__.RAST.pyr.O2	1098	1107	83	58	1335	1439
Salt_Pond_MetaGSF2_C_H2O_MG_DASTool_bins_metabat.13.contigs__.RAST.pyr.O2	1133	1133	71	52	1684	1838
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2	1287	1301	65	52	2277	2591
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_metabat.18.contigs__.RAST.pyr.O2	1015	1023	81	72	1484	1585
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.17.contigs__.RAST.pyr.O2	1009	995	129	90	1075	1158
Salt_Pond_MetaG_R1_C_D2_MG_DASTool_bins_concoct_out.36.contigs__.RAST.pyr.O2	1082	1099	84	74	1562	1676
Salt_Pond_MetaG_R1_A_D2_MG_DASTool_bins_metabat.84.contigs__.RAST.pyr.O2	458	495	309	341	262	275
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.61.contigs__.RAST.pyr.O2	953	945	168	128	1018	1144
Salt_Pond_MetaGSF2_B_H2O_MG_DASTool_bins_metabat.8.contigs__.RAST.pyr.O2	1157	1165	68	50	1765	1928
Salt_Pond_MetaG_R2A_C_D2_MG_DASTool_bins_metabat.10.contigs__.RAST.pyr.O2	1079	1091	65	49	1607	1719
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_metabat.32.contigs__.RAST.pyr.O2	989	998	110	88	1350	1492
Salt_Pond_MetaG_R2_restored_DShore_MG_DASTool_bins_concoct_out.46.contigs__.RAST.pyr.O2	1126	1137	109	87	1596	1780
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.40.contigs__.RAST.pyr.O2	1169	1159	82	54	1658	1817

957

In [20]:
model_enh['modelreactions'][0]['modelReactionProteins']

[{'complex_ref': '~/template/complexes/name/cpx00700',
  'modelReactionProteinSubunits': [{'feature_refs': ['~/genome/features/id/Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1589',
     '~/genome/features/id/Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1589_mRNA'],
    'note': 'Dihydropteroate synthase (EC 2.5.1.15)',
    'optionalSubunit': 0,
    'role': 'ftr01608',
    'triggering': 1}],
  'note': '',
  'source': 'ModelSEED'},
 {'complex_ref': '~/template/complexes/name/cpx01370',
  'modelReactionProteinSubunits': [{'feature_refs': ['~/genome/features/id/Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1507',
     '~/genome/features/id/Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs__.RAST.CDS.1507_mRNA'],
    'note': '2-amino-4-hydroxy-6-hydroxymethyldihydropteridine pyrophosphokinase (EC 2.7.6.3)',
    'optionalSubunit': 0,
    'role': 'ftr01607',
    'triggering': 1}],
  'note': '',
  'source': 'ModelSEED'}]

In [29]:
def _get_features(r):
    res = set()
    for cpx in r['modelReactionProteins']:
        for su in cpx['modelReactionProteinSubunits']:
            for f in su['feature_refs']:
                res.add(f.split('/')[-1])
    return res
def _get_all_genes(m):
    all_genes = set()
    for r in m['modelreactions']:
        all_genes |= _get_features(r)
    return all_genes

In [60]:
def _get_gapfilled_reactions(m, t):
    gapfilled = set()
    for r in m['modelreactions']:
        cpx_count = len(r['modelReactionProteins'])
        if cpx_count == 0:
            template_rxn = t.reactions.get_by_id(r['reaction_ref'].split('/')[-1])
            if template_rxn.type == 'conditional' or template_rxn.type == 'gapfilling':
                gapfilled.add(r['id'])
    return gapfilled
len(_get_gapfilled_reactions(model_reg, templates[model_reg['template_ref']]))

64